name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Build Image'
      run: |
        docker build . -f ./DockerfileDev --tag ghcr.io/the-loki/cosy-voice-dev:latest
        docker push ghcr.io/the-loki/cosy-voice-dev:latest
